[tool.poetry]
name = "nonebot_plugin_bilifan"
version = "0.0.1"
description = "刷bili粉丝牌子的机器人插件"
authors = ["Agnes_Digital <Z735803792@163.com>"]
license = "GPLv3"
readme = "README.md"
homepage = "https://github.com/Agnes4m/nonebot_plugin_l4d2_server"
repository = "https://github.com/Agnes4m/nonebot_plugin_l4d2_server"
keywords = ["bilibili", "nonebot2", "plugin"]
classifiers = [
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Operating System :: OS Independent",
]
include = [
    "LICENSE","README.md"
]

[tool.poetry.dependencies]
python = "^3.9"
nonebot2 = "^2.0.0rc4"
nonebot-adapter-onebot = ">=2.1.5"
nonebot_plugin_apscheduler = "^0.2.0"

pillow = "^9.3.0"
aiohttp = "^3.8.3"
aiohttp-socks = "^0.8.0"
pyyaml = "^6.0"
qrcode = "^7.4.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
